import { StemChar, BranchChar, Season, SeasonalModifier } from './types';

// The month branch a person is born under sets the season — the climate their
// living nature first had to grow in.
export const BRANCH_SEASON: Record<BranchChar, Season> = {
  '寅': 'Spring', '卯': 'Spring', '辰': 'Spring',
  '巳': 'Summer', '午': 'Summer', '未': 'Summer',
  '申': 'Autumn', '酉': 'Autumn', '戌': 'Autumn',
  '亥': 'Winter', '子': 'Winter', '丑': 'Winter',
};

// Per day-master, per-season climate readings, adapted from the essays.
// emphasizedNeedIds reference the need ids defined on each stem profile.
const SEASONAL: Record<StemChar, Record<Season, SeasonalModifier>> = {
  '甲': {
    Spring: { season: 'Spring', mood: 'abundant', climate: 'the rising warmth of spring',
      environmentTitle: 'Born in the growing season',
      reading: 'The tree breaks ground into soft, warm earth with water near — there is no struggle just to survive. Your work is the higher one: to grow straight and become timber that matters.',
      emphasizedNeedIds: ['sun', 'water'] },
    Summer: { season: 'Summer', mood: 'harsh', climate: 'the dry heat of summer',
      environmentTitle: 'Born into the heat',
      reading: 'A summer tree has a natural gift for showing itself, but the heat is parching. Without water you risk scorching yourself — burning out, or locking into your own head. With water, you become luminous and openly hungry to learn.',
      emphasizedNeedIds: ['water'] },
    Autumn: { season: 'Autumn', mood: 'harsh', climate: 'the cutting air of autumn',
      environmentTitle: 'Born under the axe',
      reading: 'The autumn tree is born eyed by the blade — metal is strong and the season wants to cut you down. Survival comes first: with solid ground and a little warmth you can stand secure; without them, life can feel like living on edge.',
      emphasizedNeedIds: ['root', 'sun'] },
    Winter: { season: 'Winter', mood: 'harsh', climate: 'deep winter cold',
      environmentTitle: 'Born into the frost',
      reading: 'A seed that sprouts into winter frost feels the cold of the whole sky. Cold wood does not grow — so warmth and light come before everything. A little sun early in life keeps you from hardening against the world.',
      emphasizedNeedIds: ['sun', 'root'] },
  },
  '乙': {
    Spring: { season: 'Spring', mood: 'abundant', climate: 'mild spring weather',
      environmentTitle: 'Born in fair weather',
      reading: 'Planted in the open field in spring, you grow with little pressure. With sun and gentle rain near, your sociable, graceful nature opens easily.',
      emphasizedNeedIds: ['sun', 'water'] },
    Summer: { season: 'Summer', mood: 'harsh', climate: 'the dry heat of summer',
      environmentTitle: 'Born into the heat',
      reading: 'Summer can wilt a tender plant. You need dew more than anything — gentle water to keep from drying out — so your softness stays alive rather than brittle.',
      emphasizedNeedIds: ['water', 'sun'] },
    Autumn: { season: 'Autumn', mood: 'tender', climate: 'the cooling of autumn',
      environmentTitle: 'Born at harvest time',
      reading: 'Autumn is the season the field is turned. As a tender plant you bend with circumstance rather than resist it — and warmth keeps your spirit from contracting as the world cools.',
      emphasizedNeedIds: ['sun', 'support'] },
    Winter: { season: 'Winter', mood: 'harsh', climate: 'cold winter air',
      environmentTitle: 'Born into the cold',
      reading: 'A flower in winter craves light. Without warmth your path turns roundabout and your nature folds inward; with even a little sun, your gentleness becomes grace rather than retreat.',
      emphasizedNeedIds: ['sun', 'water'] },
  },
  '丙': {
    Spring: { season: 'Spring', mood: 'balanced', climate: 'the brightening of spring',
      environmentTitle: 'Rising over a waking world',
      reading: 'The spring sun warms a world coming alive. You give light freely — and even here your real task is the inner one: clear water to see yourself by.',
      emphasizedNeedIds: ['clarity', 'land'] },
    Summer: { season: 'Summer', mood: 'harsh', climate: 'the blazing height of summer',
      environmentTitle: 'At the blazing peak',
      reading: 'At full summer you are at your most powerful — and most likely to scorch. Without clear water to cool and steady you, brilliance can tip into burning everything around you. Clarity is what keeps your fire generous.',
      emphasizedNeedIds: ['clarity'] },
    Autumn: { season: 'Autumn', mood: 'balanced', climate: 'the clear light of autumn',
      environmentTitle: 'Shining over the harvest',
      reading: 'Autumn light ripens what has grown. Your warmth has somewhere to land — and still, seeing yourself clearly is what turns your radiance into wisdom rather than glare.',
      emphasizedNeedIds: ['clarity', 'land'] },
    Winter: { season: 'Winter', mood: 'tender', climate: 'the pale light of winter',
      environmentTitle: 'A low sun over cold ground',
      reading: 'Even a winter sun cannot be put out — only veiled. Your light is needed more than ever now; clear-mindedness keeps you from running forward into the cold without knowing why.',
      emphasizedNeedIds: ['clarity', 'kindling'] },
  },
  '丁': {
    Spring: { season: 'Spring', mood: 'abundant', climate: 'the green of spring',
      environmentTitle: 'Born among plenty of fuel',
      reading: 'Spring fills the world with wood, so your flame need not fear going out. With real substance to burn and skill to shape it, you keep the long view rather than living hand-to-mouth.',
      emphasizedNeedIds: ['fuel', 'craft'] },
    Summer: { season: 'Summer', mood: 'harsh', climate: 'the heat of summer',
      environmentTitle: 'Burning in the heat',
      reading: 'In summer a small flame can devour its own fuel too fast and burn itself out. A little water keeps you steady, so your warmth lasts instead of flaring and dying.',
      emphasizedNeedIds: ['restraint', 'fuel'] },
    Autumn: { season: 'Autumn', mood: 'balanced', climate: 'the cooling of autumn',
      environmentTitle: 'Keeping the fire through autumn',
      reading: 'As the world cools, your task is continuance — keeping the flame alive and ready. Lasting fuel and the skill to tend it matter more than burning bright.',
      emphasizedNeedIds: ['fuel', 'craft'] },
    Winter: { season: 'Winter', mood: 'harsh', climate: 'deep winter cold',
      environmentTitle: 'A lantern in the dark',
      reading: 'In winter you are the light in the dark, the warmth that must not go out. With good fuel you can outlast any cold; the danger is losing heart — once the inner flame dies, it is hard to relight.',
      emphasizedNeedIds: ['fuel', 'craft'] },
  },
  '戊': {
    Spring: { season: 'Spring', mood: 'abundant', climate: 'the greening of spring',
      environmentTitle: 'A mountain coming into leaf',
      reading: 'In spring your slopes are already thick with growth, roots running deep through you. Now you need sun to lift your spirit and water to feed all that life.',
      emphasizedNeedIds: ['sun', 'water'] },
    Summer: { season: 'Summer', mood: 'harsh', climate: 'the dry heat of summer',
      environmentTitle: 'A mountain under a hard sun',
      reading: 'Summer can bake the mountain dry. First you must stay solid — not crack or hollow out — then water to keep your slopes alive, then growth to make you a living landscape.',
      emphasizedNeedIds: ['water', 'cultivate'] },
    Autumn: { season: 'Autumn', mood: 'tender', climate: 'the thinning light of autumn',
      environmentTitle: 'A mountain holding its store',
      reading: 'Autumn earth runs quiet and a little weak, but water is near. Stay solid through and through, and in time you can grow something of great worth — given warmth above all to keep your spirit up.',
      emphasizedNeedIds: ['sun', 'cultivate'] },
    Winter: { season: 'Winter', mood: 'harsh', climate: 'cold, steep winter',
      environmentTitle: 'A high mountain over rushing water',
      reading: 'Winter brings steep cold and fast water — more than the mountain can simply hold. Warmth to restore your spirit comes first, then careful tending; your lifelong lesson is knowing exactly how much you can carry.',
      emphasizedNeedIds: ['sun', 'cultivate'] },
  },
  '己': {
    Spring: { season: 'Spring', mood: 'abundant', climate: 'planting weather',
      environmentTitle: 'Sown in spring',
      reading: 'In spring the crops go in — your purpose is alive. Now nothing matters but their growth: sun when they reach for light, rain when they thirst.',
      emphasizedNeedIds: ['sun', 'water'] },
    Summer: { season: 'Summer', mood: 'harsh', climate: 'the strong sun of summer',
      environmentTitle: 'Growing under a high sun',
      reading: 'Summer light feeds everything you grow, but the heat can parch the field. You need clear sun on your crops and water against the drought, so your harvest comes in full.',
      emphasizedNeedIds: ['sun', 'water'] },
    Autumn: { season: 'Autumn', mood: 'abundant', climate: 'harvest light',
      environmentTitle: 'Ripening toward harvest',
      reading: 'The crops near ripeness, and the old line holds: the stronger the sun, the better the grain. Warmth matters most now — your worth is about to become plain in the harvest.',
      emphasizedNeedIds: ['sun', 'cultivate'] },
    Winter: { season: 'Winter', mood: 'tender', climate: 'the resting cold of winter',
      environmentTitle: 'Fallow ground in winter',
      reading: 'In winter the field rests and slowly restores itself for the year to come. Early life may feel slow or unrewarded, but you often come into your own later — a deliberate, late-ripening strength.',
      emphasizedNeedIds: ['sun', 'water'] },
  },
  '庚': {
    Spring: { season: 'Spring', mood: 'balanced', climate: 'the fresh air of spring',
      environmentTitle: 'Ore waiting for the forge',
      reading: 'Young and unshaped, you are raw metal waiting to be made useful. Fire to forge you — real trials and refinement — is what turns rough strength into a blade that can cut.',
      emphasizedNeedIds: ['forge'] },
    Summer: { season: 'Summer', mood: 'balanced', climate: 'the heat of summer',
      environmentTitle: 'Glowing in the forge',
      reading: 'Summer brings fire in plenty — you are well forged. The risk is over-hardening: once shaped, a blade kept in the fire only warps. Now water to temper you matters, so strength gains resilience.',
      emphasizedNeedIds: ['temper', 'forge'] },
    Autumn: { season: 'Autumn', mood: 'abundant', climate: 'the strength of metal season',
      environmentTitle: 'Metal in its own season',
      reading: 'Autumn is metal’s own season — you are strong, perhaps too strong. Both fire to shape you and water to temper you keep that strength from turning brittle and unbending.',
      emphasizedNeedIds: ['forge', 'temper'] },
    Winter: { season: 'Winter', mood: 'harsh', climate: 'the cold of winter',
      environmentTitle: 'Cold iron',
      reading: 'Winter metal runs cold and water is everywhere. What you need is fire — the forge’s heat to shape and warm you — or you stay a blunt, unfinished tool rather than a true blade.',
      emphasizedNeedIds: ['forge'] },
  },
  '辛': {
    Spring: { season: 'Spring', mood: 'tender', climate: 'the soft light of spring',
      environmentTitle: 'A gem in gentle light',
      reading: 'Spring metal is at its most delicate. Clear water to keep you bright, with a little warmth, lets your quality begin to show without strain.',
      emphasizedNeedIds: ['cleanse', 'light'] },
    Summer: { season: 'Summer', mood: 'harsh', climate: 'the harsh glare of summer',
      environmentTitle: 'A jewel under harsh light',
      reading: 'Summer’s fierce light can pressure a sensitive stone. Clear water comes first — to wash you bright and keep you cool — so the heat reveals your shine instead of overwhelming you.',
      emphasizedNeedIds: ['cleanse'] },
    Autumn: { season: 'Autumn', mood: 'abundant', climate: 'the clarity of autumn',
      environmentTitle: 'A gem in its season',
      reading: 'Autumn suits you — clear and bright. Water to keep you spotless lets your natural elegance be seen at its best; your gift is being recognized for what you truly are.',
      emphasizedNeedIds: ['cleanse', 'space'] },
    Winter: { season: 'Winter', mood: 'harsh', climate: 'cold winter light',
      environmentTitle: 'A jewel in winter light',
      reading: 'Winter is cold and dim. You need both warmth and clear water — light to be seen by and water to stay bright — so you are neither frozen over nor hidden away.',
      emphasizedNeedIds: ['light', 'cleanse'] },
  },
  '壬': {
    Spring: { season: 'Spring', mood: 'harsh', climate: 'the draining green of spring',
      environmentTitle: 'A river running thin',
      reading: 'Spring growth drinks your water down and pulls you in many directions. A guiding channel — structure and principle — both points your flow and quiets the overthinking.',
      emphasizedNeedIds: ['direction'] },
    Summer: { season: 'Summer', mood: 'balanced', climate: 'the strong sun of summer',
      environmentTitle: 'Open water under a high sun',
      reading: 'Summer light spreads wide across the water, showing its breadth. An outlet to express your power turns your vastness into visible results — and clear water keeps you from churning.',
      emphasizedNeedIds: ['expression', 'clarity'] },
    Autumn: { season: 'Autumn', mood: 'abundant', climate: 'the clear cool of autumn',
      environmentTitle: 'Clear water, clean banks',
      reading: 'Autumn can clog the river with silt; your work is to keep the channel clear. Stay unmuddied and well-directed, and clear water over clean stone makes for genuine refinement.',
      emphasizedNeedIds: ['direction', 'clarity'] },
    Winter: { season: 'Winter', mood: 'harsh', climate: 'the swelling cold of winter',
      environmentTitle: 'A river in full, cold flood',
      reading: 'Winter swells you to a flood — powerful but cold and overspilling. Warmth and an outlet to express yourself keep that force from turning inward into self-absorption.',
      emphasizedNeedIds: ['expression', 'direction'] },
  },
  '癸': {
    Spring: { season: 'Spring', mood: 'abundant', climate: 'planting weather',
      environmentTitle: 'Spring rain on new fields',
      reading: 'In spring you fall on freshly sown ground and things reach for the light. With a little sun your gentle water becomes the very weather growth needs.',
      emphasizedNeedIds: ['sun', 'purpose'] },
    Summer: { season: 'Summer', mood: 'harsh', climate: 'the drought-heat of summer',
      environmentTitle: 'Rain in a dry season',
      reading: 'In summer your rain is most needed and most precious. Falling on living crops, your care is treasured; what gives you meaning is seeing it bear fruit, not falling on barren ground.',
      emphasizedNeedIds: ['purpose', 'sun'] },
    Autumn: { season: 'Autumn', mood: 'balanced', climate: 'the clear air of autumn',
      environmentTitle: 'Dew before the harvest',
      reading: 'At harvest, sun matters more than rain — too much water now can spoil the grain. Your clear, unclouded devotion reads as quiet nobility when you know when to give and when to rest.',
      emphasizedNeedIds: ['sun', 'purpose'] },
    Winter: { season: 'Winter', mood: 'harsh', climate: 'freezing winter',
      environmentTitle: 'Cold rain in winter',
      reading: 'The more water, the colder the world — and winter rain can chill rather than nourish. Warmth and a real purpose to fall toward keep your giving from turning cold and unrewarded.',
      emphasizedNeedIds: ['sun', 'purpose'] },
  },
};

export function resolveSeasonalModifier(stem: StemChar, branch: BranchChar): SeasonalModifier {
  const season = BRANCH_SEASON[branch];
  return SEASONAL[stem][season];
}
